// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/payment/payment.proto

package payment

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Payment struct {
	Transacno            int64    `protobuf:"varint,1,opt,name=transacno,proto3" json:"transacno,omitempty"`
	Nomclient            string   `protobuf:"bytes,2,opt,name=nomclient,proto3" json:"nomclient,omitempty"`
	Prenomclient         string   `protobuf:"bytes,3,opt,name=prenomclient,proto3" json:"prenomclient,omitempty"`
	Telephone            string   `protobuf:"bytes,4,opt,name=telephone,proto3" json:"telephone,omitempty"`
	Datepaymentuser      string   `protobuf:"bytes,5,opt,name=datepaymentuser,proto3" json:"datepaymentuser,omitempty"`
	Conventionno         int32    `protobuf:"varint,6,opt,name=conventionno,proto3" json:"conventionno,omitempty"`
	Policeno             int32    `protobuf:"varint,7,opt,name=policeno,proto3" json:"policeno,omitempty"`
	Montant              int64    `protobuf:"varint,8,opt,name=montant,proto3" json:"montant,omitempty"`
	CreatedAt            string   `protobuf:"bytes,9,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Payment) Reset()         { *m = Payment{} }
func (m *Payment) String() string { return proto.CompactTextString(m) }
func (*Payment) ProtoMessage()    {}
func (*Payment) Descriptor() ([]byte, []int) {
	return fileDescriptor_78ce6d11f0608d17, []int{0}
}

func (m *Payment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Payment.Unmarshal(m, b)
}
func (m *Payment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Payment.Marshal(b, m, deterministic)
}
func (m *Payment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Payment.Merge(m, src)
}
func (m *Payment) XXX_Size() int {
	return xxx_messageInfo_Payment.Size(m)
}
func (m *Payment) XXX_DiscardUnknown() {
	xxx_messageInfo_Payment.DiscardUnknown(m)
}

var xxx_messageInfo_Payment proto.InternalMessageInfo

func (m *Payment) GetTransacno() int64 {
	if m != nil {
		return m.Transacno
	}
	return 0
}

func (m *Payment) GetNomclient() string {
	if m != nil {
		return m.Nomclient
	}
	return ""
}

func (m *Payment) GetPrenomclient() string {
	if m != nil {
		return m.Prenomclient
	}
	return ""
}

func (m *Payment) GetTelephone() string {
	if m != nil {
		return m.Telephone
	}
	return ""
}

func (m *Payment) GetDatepaymentuser() string {
	if m != nil {
		return m.Datepaymentuser
	}
	return ""
}

func (m *Payment) GetConventionno() int32 {
	if m != nil {
		return m.Conventionno
	}
	return 0
}

func (m *Payment) GetPoliceno() int32 {
	if m != nil {
		return m.Policeno
	}
	return 0
}

func (m *Payment) GetMontant() int64 {
	if m != nil {
		return m.Montant
	}
	return 0
}

func (m *Payment) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

type Response struct {
	Done                 bool     `protobuf:"varint,1,opt,name=done,proto3" json:"done,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Payment              *Payment `protobuf:"bytes,3,opt,name=payment,proto3" json:"payment,omitempty"`
	Errors               []*Error `protobuf:"bytes,4,rep,name=errors,proto3" json:"errors,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_78ce6d11f0608d17, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetDone() bool {
	if m != nil {
		return m.Done
	}
	return false
}

func (m *Response) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Response) GetPayment() *Payment {
	if m != nil {
		return m.Payment
	}
	return nil
}

func (m *Response) GetErrors() []*Error {
	if m != nil {
		return m.Errors
	}
	return nil
}

type Error struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_78ce6d11f0608d17, []int{2}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Error) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func init() {
	proto.RegisterType((*Payment)(nil), "payment.Payment")
	proto.RegisterType((*Response)(nil), "payment.Response")
	proto.RegisterType((*Error)(nil), "payment.Error")
}

func init() {
	proto.RegisterFile("proto/payment/payment.proto", fileDescriptor_78ce6d11f0608d17)
}

var fileDescriptor_78ce6d11f0608d17 = []byte{
	// 339 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0xcf, 0x4e, 0xe3, 0x30,
	0x10, 0xc6, 0x37, 0x4d, 0xd3, 0xa4, 0xd3, 0x55, 0x77, 0xd7, 0x27, 0xab, 0xcb, 0x21, 0xca, 0x01,
	0x45, 0x08, 0x15, 0xa9, 0x9c, 0x41, 0xe2, 0xc0, 0xbd, 0x32, 0x4f, 0x10, 0x9c, 0x91, 0x88, 0xd4,
	0xce, 0x58, 0x8e, 0xa9, 0xd4, 0xf7, 0xe0, 0x25, 0x78, 0x4b, 0x64, 0xe7, 0x4f, 0x29, 0x1c, 0x38,
	0x65, 0xe6, 0x37, 0x9f, 0xec, 0xcf, 0xdf, 0x04, 0xfe, 0x1b, 0xcb, 0x8e, 0x6f, 0x4c, 0x75, 0xdc,
	0x23, 0xb9, 0xe1, 0xbb, 0x0e, 0x54, 0xa4, 0x7d, 0x5b, 0xbc, 0x4f, 0x20, 0xdd, 0x76, 0xb5, 0xb8,
	0x80, 0xb9, 0xb3, 0x15, 0xb5, 0x95, 0x26, 0x96, 0x51, 0x1e, 0x95, 0xb1, 0x3a, 0x01, 0x3f, 0x25,
	0xde, 0xeb, 0x5d, 0x83, 0xe4, 0xe4, 0x24, 0x8f, 0xca, 0xb9, 0x3a, 0x01, 0x51, 0xc0, 0x6f, 0x63,
	0xf1, 0x24, 0x88, 0x83, 0xe0, 0x8c, 0x85, 0xf3, 0x71, 0x87, 0xe6, 0x85, 0x09, 0xe5, 0xb4, 0x3b,
	0x61, 0x04, 0xa2, 0x84, 0x3f, 0x75, 0xe5, 0xb0, 0x37, 0xf6, 0xda, 0xa2, 0x95, 0x49, 0xd0, 0x7c,
	0xc5, 0xfe, 0x2e, 0xcd, 0x74, 0x40, 0x72, 0x0d, 0x13, 0xb1, 0x9c, 0xe5, 0x51, 0x99, 0xa8, 0x33,
	0x26, 0x56, 0x90, 0x19, 0xde, 0x35, 0x1a, 0x89, 0x65, 0x1a, 0xe6, 0x63, 0x2f, 0x24, 0xa4, 0x7b,
	0x26, 0x57, 0x91, 0x93, 0x59, 0x78, 0xe5, 0xd0, 0x7a, 0x87, 0xda, 0x62, 0xe5, 0xb0, 0x7e, 0x70,
	0x72, 0xde, 0x39, 0x1c, 0x41, 0xf1, 0x16, 0x41, 0xa6, 0xb0, 0x35, 0x4c, 0x2d, 0x0a, 0x01, 0xd3,
	0xda, 0xbf, 0xc3, 0xe7, 0x94, 0xa9, 0x50, 0x8b, 0x1c, 0x16, 0x35, 0xb6, 0xda, 0x36, 0xc6, 0xbb,
	0xe8, 0x43, 0xfa, 0x8c, 0xc4, 0x15, 0x0c, 0xc9, 0x87, 0x84, 0x16, 0x9b, 0xbf, 0xeb, 0x61, 0x31,
	0xfd, 0x16, 0xd4, 0x20, 0x10, 0x97, 0x30, 0x43, 0x6b, 0xd9, 0xb6, 0x72, 0x9a, 0xc7, 0xe5, 0x62,
	0xb3, 0x1c, 0xa5, 0x8f, 0x1e, 0xab, 0x7e, 0x5a, 0xdc, 0x41, 0x12, 0x80, 0xb7, 0xa4, 0xb9, 0xee,
	0x2c, 0x25, 0x2a, 0xd4, 0x3f, 0x5b, 0xda, 0xdc, 0xc3, 0xb2, 0xbf, 0xfa, 0x09, 0xed, 0xa1, 0xd1,
	0x28, 0xae, 0x21, 0xde, 0x56, 0x47, 0xf1, 0xcd, 0xda, 0xea, 0xdf, 0x48, 0x86, 0x18, 0x8a, 0x5f,
	0xcf, 0xb3, 0xf0, 0x47, 0xdd, 0x7e, 0x04, 0x00, 0x00, 0xff, 0xff, 0x99, 0xa1, 0x11, 0xca, 0x70,
	0x02, 0x00, 0x00,
}
