// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/prestation/prestation.proto

package prestation

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Prestation struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Transacno            string   `protobuf:"bytes,2,opt,name=transacno,proto3" json:"transacno,omitempty"`
	Nomclient            string   `protobuf:"bytes,3,opt,name=nomclient,proto3" json:"nomclient,omitempty"`
	Prenomclient         string   `protobuf:"bytes,4,opt,name=prenomclient,proto3" json:"prenomclient,omitempty"`
	Telephone            string   `protobuf:"bytes,5,opt,name=telephone,proto3" json:"telephone,omitempty"`
	Datedamandeuser      string   `protobuf:"bytes,6,opt,name=datedamandeuser,proto3" json:"datedamandeuser,omitempty"`
	Conventionno         string   `protobuf:"bytes,7,opt,name=conventionno,proto3" json:"conventionno,omitempty"`
	Policeno             string   `protobuf:"bytes,8,opt,name=policeno,proto3" json:"policeno,omitempty"`
	Montantdemande       string   `protobuf:"bytes,9,opt,name=montantdemande,proto3" json:"montantdemande,omitempty"`
	Montantrestant       string   `protobuf:"bytes,10,opt,name=montantrestant,proto3" json:"montantrestant,omitempty"`
	CreatedAt            string   `protobuf:"bytes,11,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Prestation) Reset()         { *m = Prestation{} }
func (m *Prestation) String() string { return proto.CompactTextString(m) }
func (*Prestation) ProtoMessage()    {}
func (*Prestation) Descriptor() ([]byte, []int) {
	return fileDescriptor_9d4002c97688aaf2, []int{0}
}

func (m *Prestation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Prestation.Unmarshal(m, b)
}
func (m *Prestation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Prestation.Marshal(b, m, deterministic)
}
func (m *Prestation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Prestation.Merge(m, src)
}
func (m *Prestation) XXX_Size() int {
	return xxx_messageInfo_Prestation.Size(m)
}
func (m *Prestation) XXX_DiscardUnknown() {
	xxx_messageInfo_Prestation.DiscardUnknown(m)
}

var xxx_messageInfo_Prestation proto.InternalMessageInfo

func (m *Prestation) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Prestation) GetTransacno() string {
	if m != nil {
		return m.Transacno
	}
	return ""
}

func (m *Prestation) GetNomclient() string {
	if m != nil {
		return m.Nomclient
	}
	return ""
}

func (m *Prestation) GetPrenomclient() string {
	if m != nil {
		return m.Prenomclient
	}
	return ""
}

func (m *Prestation) GetTelephone() string {
	if m != nil {
		return m.Telephone
	}
	return ""
}

func (m *Prestation) GetDatedamandeuser() string {
	if m != nil {
		return m.Datedamandeuser
	}
	return ""
}

func (m *Prestation) GetConventionno() string {
	if m != nil {
		return m.Conventionno
	}
	return ""
}

func (m *Prestation) GetPoliceno() string {
	if m != nil {
		return m.Policeno
	}
	return ""
}

func (m *Prestation) GetMontantdemande() string {
	if m != nil {
		return m.Montantdemande
	}
	return ""
}

func (m *Prestation) GetMontantrestant() string {
	if m != nil {
		return m.Montantrestant
	}
	return ""
}

func (m *Prestation) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

type Request struct {
	Police               int32    `protobuf:"varint,1,opt,name=police,proto3" json:"police,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_9d4002c97688aaf2, []int{1}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetPolice() int32 {
	if m != nil {
		return m.Police
	}
	return 0
}

type Response struct {
	Done                 bool        `protobuf:"varint,1,opt,name=done,proto3" json:"done,omitempty"`
	Description          string      `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Maximumrachetable    string      `protobuf:"bytes,3,opt,name=maximumrachetable,proto3" json:"maximumrachetable,omitempty"`
	Prestation           *Prestation `protobuf:"bytes,4,opt,name=prestation,proto3" json:"prestation,omitempty"`
	Errors               []*Error    `protobuf:"bytes,5,rep,name=errors,proto3" json:"errors,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_9d4002c97688aaf2, []int{2}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetDone() bool {
	if m != nil {
		return m.Done
	}
	return false
}

func (m *Response) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Response) GetMaximumrachetable() string {
	if m != nil {
		return m.Maximumrachetable
	}
	return ""
}

func (m *Response) GetPrestation() *Prestation {
	if m != nil {
		return m.Prestation
	}
	return nil
}

func (m *Response) GetErrors() []*Error {
	if m != nil {
		return m.Errors
	}
	return nil
}

type Error struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_9d4002c97688aaf2, []int{3}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Error) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func init() {
	proto.RegisterType((*Prestation)(nil), "prestation.Prestation")
	proto.RegisterType((*Request)(nil), "prestation.Request")
	proto.RegisterType((*Response)(nil), "prestation.Response")
	proto.RegisterType((*Error)(nil), "prestation.Error")
}

func init() {
	proto.RegisterFile("proto/prestation/prestation.proto", fileDescriptor_9d4002c97688aaf2)
}

var fileDescriptor_9d4002c97688aaf2 = []byte{
	// 423 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x93, 0xc1, 0x6a, 0x1b, 0x31,
	0x10, 0x86, 0x6b, 0x27, 0xde, 0xd8, 0xe3, 0x90, 0xe2, 0x69, 0x09, 0x22, 0xf4, 0xe0, 0xec, 0xa1,
	0xb8, 0x50, 0x52, 0x70, 0xa1, 0x14, 0x4a, 0x0f, 0x3d, 0xf4, 0x5e, 0x54, 0xe8, 0x5d, 0x91, 0x06,
	0x2c, 0xd8, 0x95, 0xb6, 0x92, 0x1c, 0xfa, 0x0c, 0x7d, 0xbb, 0xbe, 0x4a, 0x9f, 0xa0, 0x68, 0xbc,
	0xf6, 0xca, 0x29, 0x26, 0x37, 0xe9, 0xfb, 0x7f, 0x69, 0xe7, 0x9f, 0xd1, 0xc2, 0x6d, 0x17, 0x7c,
	0xf2, 0xef, 0xba, 0x40, 0x31, 0xa9, 0x64, 0xbd, 0x2b, 0x96, 0x77, 0xac, 0x21, 0x0c, 0xa4, 0xfe,
	0x3b, 0x06, 0xf8, 0x76, 0xd8, 0xe2, 0x15, 0x8c, 0xad, 0x11, 0xa3, 0xe5, 0x68, 0x35, 0x93, 0x63,
	0x6b, 0xf0, 0x15, 0xcc, 0x52, 0x50, 0x2e, 0x2a, 0xed, 0xbc, 0x18, 0x33, 0x1e, 0x40, 0x56, 0x9d,
	0x6f, 0x75, 0x63, 0xc9, 0x25, 0x71, 0xb6, 0x53, 0x0f, 0x00, 0x6b, 0xb8, 0xec, 0x02, 0x0d, 0x86,
	0x73, 0x36, 0x1c, 0x31, 0xbe, 0x9f, 0x1a, 0xea, 0x36, 0xde, 0x91, 0x98, 0xf4, 0xf7, 0xef, 0x01,
	0xae, 0xe0, 0xb9, 0x51, 0x89, 0x8c, 0x6a, 0x95, 0x33, 0xb4, 0x8d, 0x14, 0x44, 0xc5, 0x9e, 0xc7,
	0x38, 0x7f, 0x4b, 0x7b, 0xf7, 0x40, 0x2e, 0xa7, 0x70, 0x5e, 0x5c, 0xec, 0xbe, 0x55, 0x32, 0xbc,
	0x81, 0x69, 0xe7, 0x1b, 0xab, 0xc9, 0x79, 0x31, 0x65, 0xfd, 0xb0, 0xc7, 0xd7, 0x70, 0xd5, 0x7a,
	0x97, 0x94, 0x4b, 0x86, 0xf8, 0x56, 0x31, 0x63, 0xc7, 0x23, 0x5a, 0xf8, 0xb8, 0x67, 0x2e, 0x09,
	0x38, 0xf2, 0xf5, 0x34, 0xe7, 0xd2, 0x81, 0x72, 0x91, 0x5f, 0x92, 0x98, 0xef, 0x72, 0x1d, 0x40,
	0x7d, 0x0b, 0x17, 0x92, 0x7e, 0x6e, 0x29, 0x26, 0xbc, 0x86, 0x6a, 0x57, 0x04, 0x37, 0x7d, 0x22,
	0xfb, 0x5d, 0xfd, 0x67, 0x04, 0x53, 0x49, 0xb1, 0xf3, 0x2e, 0x12, 0x22, 0x9c, 0x9b, 0xdc, 0xa0,
	0x6c, 0x99, 0x4a, 0x5e, 0xe3, 0x12, 0xe6, 0x86, 0xa2, 0x0e, 0xb6, 0xcb, 0xf1, 0xfa, 0xd9, 0x94,
	0x08, 0xdf, 0xc2, 0xa2, 0x55, 0xbf, 0x6c, 0xbb, 0x6d, 0x83, 0xd2, 0x1b, 0x4a, 0xea, 0xbe, 0xa1,
	0x7e, 0x4a, 0xff, 0x0b, 0xf8, 0x01, 0x8a, 0x67, 0xc1, 0xb3, 0x9a, 0xaf, 0xaf, 0xef, 0x8a, 0xb7,
	0x33, 0xbc, 0x12, 0x59, 0x38, 0xf1, 0x0d, 0x54, 0x14, 0x82, 0x0f, 0x51, 0x4c, 0x96, 0x67, 0xab,
	0xf9, 0x7a, 0x51, 0x9e, 0xf9, 0x9a, 0x15, 0xd9, 0x1b, 0xea, 0xcf, 0x30, 0x61, 0x90, 0xf3, 0x68,
	0x6f, 0xf6, 0x91, 0x79, 0xfd, 0x74, 0x9e, 0xf5, 0xef, 0x11, 0x2c, 0x86, 0x22, 0xbe, 0x53, 0x78,
	0xb0, 0x9a, 0xf0, 0x23, 0x54, 0x52, 0xe9, 0x8d, 0x4a, 0x78, 0xa2, 0xda, 0x9b, 0x97, 0x25, 0xdf,
	0xf7, 0xb4, 0x7e, 0x86, 0x9f, 0xe0, 0xf2, 0x87, 0x6a, 0x68, 0x1b, 0xfa, 0xf3, 0x2f, 0x8e, 0x7d,
	0x3c, 0x9f, 0x53, 0x87, 0xef, 0x2b, 0xfe, 0x95, 0xde, 0xff, 0x0b, 0x00, 0x00, 0xff, 0xff, 0x15,
	0x4f, 0x4d, 0xe7, 0x6f, 0x03, 0x00, 0x00,
}
