// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/souscription/souscription.proto

package souscription

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Souscription struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Nom                  string   `protobuf:"bytes,2,opt,name=nom,proto3" json:"nom,omitempty"`
	Prenom               string   `protobuf:"bytes,3,opt,name=prenom,proto3" json:"prenom,omitempty"`
	Dateofbith           string   `protobuf:"bytes,4,opt,name=dateofbith,proto3" json:"dateofbith,omitempty"`
	Telephone            string   `protobuf:"bytes,5,opt,name=telephone,proto3" json:"telephone,omitempty"`
	Abjcardno            uint32   `protobuf:"fixed32,6,opt,name=abjcardno,proto3" json:"abjcardno,omitempty"`
	Montant              uint64   `protobuf:"varint,7,opt,name=montant,proto3" json:"montant,omitempty"`
	Codeproduit          int32    `protobuf:"varint,8,opt,name=codeproduit,proto3" json:"codeproduit,omitempty"`
	Datepayment          string   `protobuf:"bytes,9,opt,name=datepayment,proto3" json:"datepayment,omitempty"`
	Echeance             string   `protobuf:"bytes,10,opt,name=echeance,proto3" json:"echeance,omitempty"`
	Beneficiaire         string   `protobuf:"bytes,11,opt,name=beneficiaire,proto3" json:"beneficiaire,omitempty"`
	Email                string   `protobuf:"bytes,12,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Souscription) Reset()         { *m = Souscription{} }
func (m *Souscription) String() string { return proto.CompactTextString(m) }
func (*Souscription) ProtoMessage()    {}
func (*Souscription) Descriptor() ([]byte, []int) {
	return fileDescriptor_7284ccaf0eb6016c, []int{0}
}

func (m *Souscription) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Souscription.Unmarshal(m, b)
}
func (m *Souscription) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Souscription.Marshal(b, m, deterministic)
}
func (m *Souscription) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Souscription.Merge(m, src)
}
func (m *Souscription) XXX_Size() int {
	return xxx_messageInfo_Souscription.Size(m)
}
func (m *Souscription) XXX_DiscardUnknown() {
	xxx_messageInfo_Souscription.DiscardUnknown(m)
}

var xxx_messageInfo_Souscription proto.InternalMessageInfo

func (m *Souscription) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Souscription) GetNom() string {
	if m != nil {
		return m.Nom
	}
	return ""
}

func (m *Souscription) GetPrenom() string {
	if m != nil {
		return m.Prenom
	}
	return ""
}

func (m *Souscription) GetDateofbith() string {
	if m != nil {
		return m.Dateofbith
	}
	return ""
}

func (m *Souscription) GetTelephone() string {
	if m != nil {
		return m.Telephone
	}
	return ""
}

func (m *Souscription) GetAbjcardno() uint32 {
	if m != nil {
		return m.Abjcardno
	}
	return 0
}

func (m *Souscription) GetMontant() uint64 {
	if m != nil {
		return m.Montant
	}
	return 0
}

func (m *Souscription) GetCodeproduit() int32 {
	if m != nil {
		return m.Codeproduit
	}
	return 0
}

func (m *Souscription) GetDatepayment() string {
	if m != nil {
		return m.Datepayment
	}
	return ""
}

func (m *Souscription) GetEcheance() string {
	if m != nil {
		return m.Echeance
	}
	return ""
}

func (m *Souscription) GetBeneficiaire() string {
	if m != nil {
		return m.Beneficiaire
	}
	return ""
}

func (m *Souscription) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type Request struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_7284ccaf0eb6016c, []int{1}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

type Response struct {
	Done                 bool            `protobuf:"varint,1,opt,name=done,proto3" json:"done,omitempty"`
	Souscription         *Souscription   `protobuf:"bytes,2,opt,name=souscription,proto3" json:"souscription,omitempty"`
	Souscriptions        []*Souscription `protobuf:"bytes,3,rep,name=souscriptions,proto3" json:"souscriptions,omitempty"`
	Errors               []*Error        `protobuf:"bytes,4,rep,name=errors,proto3" json:"errors,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_7284ccaf0eb6016c, []int{2}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetDone() bool {
	if m != nil {
		return m.Done
	}
	return false
}

func (m *Response) GetSouscription() *Souscription {
	if m != nil {
		return m.Souscription
	}
	return nil
}

func (m *Response) GetSouscriptions() []*Souscription {
	if m != nil {
		return m.Souscriptions
	}
	return nil
}

func (m *Response) GetErrors() []*Error {
	if m != nil {
		return m.Errors
	}
	return nil
}

type Error struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_7284ccaf0eb6016c, []int{3}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Error) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func init() {
	proto.RegisterType((*Souscription)(nil), "souscription.Souscription")
	proto.RegisterType((*Request)(nil), "souscription.Request")
	proto.RegisterType((*Response)(nil), "souscription.Response")
	proto.RegisterType((*Error)(nil), "souscription.Error")
}

func init() {
	proto.RegisterFile("proto/souscription/souscription.proto", fileDescriptor_7284ccaf0eb6016c)
}

var fileDescriptor_7284ccaf0eb6016c = []byte{
	// 421 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x93, 0x51, 0x8b, 0xd3, 0x40,
	0x10, 0xc7, 0x4d, 0xdb, 0xa4, 0xcd, 0xb4, 0x8a, 0xcc, 0xe9, 0xb1, 0x14, 0x91, 0x10, 0x10, 0x0a,
	0xc2, 0x09, 0xe7, 0x93, 0xa0, 0xe2, 0x81, 0xe2, 0xfb, 0xf6, 0x13, 0x6c, 0x92, 0x39, 0xba, 0x92,
	0xee, 0xc6, 0xcd, 0x46, 0xf0, 0x43, 0xfa, 0xe0, 0x9b, 0x1f, 0x47, 0x76, 0xbc, 0xb3, 0xbb, 0x3e,
	0x9c, 0x70, 0x6f, 0xfb, 0xff, 0xfd, 0x67, 0xda, 0x99, 0xff, 0x10, 0x78, 0x31, 0x38, 0xeb, 0xed,
	0xab, 0xd1, 0x4e, 0x63, 0xeb, 0xf4, 0xe0, 0xb5, 0x35, 0x89, 0xb8, 0x60, 0x1f, 0x37, 0x31, 0xab,
	0x7f, 0xcd, 0x60, 0xb3, 0x8f, 0x00, 0x3e, 0x82, 0x99, 0xee, 0x44, 0x56, 0x65, 0xbb, 0x52, 0xce,
	0x74, 0x87, 0x8f, 0x61, 0x6e, 0xec, 0x51, 0xcc, 0x18, 0x84, 0x27, 0x9e, 0x43, 0x31, 0x38, 0x0a,
	0x70, 0xce, 0xf0, 0x46, 0xe1, 0x73, 0x80, 0x4e, 0x79, 0xb2, 0xd7, 0x8d, 0xf6, 0x07, 0xb1, 0x60,
	0x2f, 0x22, 0xf8, 0x0c, 0x4a, 0x4f, 0x3d, 0x0d, 0x07, 0x6b, 0x48, 0xe4, 0x6c, 0x9f, 0x40, 0x70,
	0x55, 0xf3, 0xa5, 0x55, 0xae, 0x33, 0x56, 0x14, 0x55, 0xb6, 0x5b, 0xca, 0x13, 0x40, 0x01, 0xcb,
	0xa3, 0x35, 0x5e, 0x19, 0x2f, 0x96, 0x55, 0xb6, 0x5b, 0xc8, 0x5b, 0x89, 0x15, 0xac, 0x5b, 0xdb,
	0xd1, 0xe0, 0x6c, 0x37, 0x69, 0x2f, 0x56, 0x55, 0xb6, 0xcb, 0x65, 0x8c, 0x42, 0x45, 0x98, 0x62,
	0x50, 0xdf, 0x8f, 0x64, 0xbc, 0x28, 0xf9, 0x9f, 0x63, 0x84, 0x5b, 0x58, 0x51, 0x7b, 0x20, 0x65,
	0x5a, 0x12, 0xc0, 0xf6, 0x5f, 0x8d, 0x35, 0x6c, 0x1a, 0x32, 0x74, 0xad, 0x5b, 0xad, 0xb4, 0x23,
	0xb1, 0x66, 0x3f, 0x61, 0xf8, 0x04, 0x72, 0x3a, 0x2a, 0xdd, 0x8b, 0x0d, 0x9b, 0x7f, 0x44, 0x5d,
	0xc2, 0x52, 0xd2, 0xd7, 0x89, 0x46, 0x5f, 0xff, 0xc8, 0x60, 0x25, 0x69, 0x1c, 0xac, 0x19, 0x09,
	0x11, 0x16, 0x5d, 0x88, 0x20, 0x64, 0xbc, 0x92, 0xfc, 0xc6, 0xf7, 0x90, 0x9c, 0x85, 0xe3, 0x5e,
	0x5f, 0x6e, 0x2f, 0x92, 0xfb, 0xc5, 0x77, 0x92, 0x49, 0x3d, 0x7e, 0x80, 0x87, 0xb1, 0x1e, 0xc5,
	0xbc, 0x9a, 0xff, 0xe7, 0x07, 0xd2, 0x06, 0x7c, 0x09, 0x05, 0x39, 0x67, 0xdd, 0x28, 0x16, 0xdc,
	0x7a, 0x96, 0xb6, 0x7e, 0x0a, 0x9e, 0xbc, 0x29, 0xa9, 0xdf, 0x41, 0xce, 0x20, 0xec, 0x12, 0xa2,
	0xe6, 0x5d, 0x72, 0xc9, 0x6f, 0xce, 0x9b, 0xd2, 0x55, 0x42, 0xde, 0x27, 0x74, 0xf9, 0x33, 0x83,
	0xb3, 0x78, 0x96, 0x3d, 0xb9, 0x6f, 0xba, 0x25, 0xbc, 0x82, 0x72, 0x3f, 0x35, 0x01, 0x37, 0x84,
	0x77, 0xcc, 0xbe, 0x3d, 0x4f, 0xbd, 0xdb, 0x68, 0xeb, 0x07, 0xf8, 0x06, 0x8a, 0xcf, 0xe4, 0xaf,
	0xfa, 0x1e, 0x9f, 0xfe, 0x5b, 0xc3, 0xa7, 0xb8, 0xa3, 0xf5, 0x2d, 0x94, 0x1f, 0xa9, 0x27, 0x4f,
	0xf7, 0xe9, 0x6e, 0x0a, 0xfe, 0xba, 0x5e, 0xff, 0x0e, 0x00, 0x00, 0xff, 0xff, 0xa1, 0xbd, 0x7f,
	0x3b, 0x86, 0x03, 0x00, 0x00,
}
