// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/product/product.proto

package product

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Client struct {
	Nom                  string   `protobuf:"bytes,1,opt,name=nom,proto3" json:"nom,omitempty"`
	Prenom               string   `protobuf:"bytes,2,opt,name=prenom,proto3" json:"prenom,omitempty"`
	Dateofbirth          string   `protobuf:"bytes,3,opt,name=dateofbirth,proto3" json:"dateofbirth,omitempty"`
	Abjcardno            string   `protobuf:"bytes,4,opt,name=abjcardno,proto3" json:"abjcardno,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Client) Reset()         { *m = Client{} }
func (m *Client) String() string { return proto.CompactTextString(m) }
func (*Client) ProtoMessage()    {}
func (*Client) Descriptor() ([]byte, []int) {
	return fileDescriptor_14fbc13de7c38f78, []int{0}
}

func (m *Client) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Client.Unmarshal(m, b)
}
func (m *Client) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Client.Marshal(b, m, deterministic)
}
func (m *Client) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Client.Merge(m, src)
}
func (m *Client) XXX_Size() int {
	return xxx_messageInfo_Client.Size(m)
}
func (m *Client) XXX_DiscardUnknown() {
	xxx_messageInfo_Client.DiscardUnknown(m)
}

var xxx_messageInfo_Client proto.InternalMessageInfo

func (m *Client) GetNom() string {
	if m != nil {
		return m.Nom
	}
	return ""
}

func (m *Client) GetPrenom() string {
	if m != nil {
		return m.Prenom
	}
	return ""
}

func (m *Client) GetDateofbirth() string {
	if m != nil {
		return m.Dateofbirth
	}
	return ""
}

func (m *Client) GetAbjcardno() string {
	if m != nil {
		return m.Abjcardno
	}
	return ""
}

type Product struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Product) Reset()         { *m = Product{} }
func (m *Product) String() string { return proto.CompactTextString(m) }
func (*Product) ProtoMessage()    {}
func (*Product) Descriptor() ([]byte, []int) {
	return fileDescriptor_14fbc13de7c38f78, []int{1}
}

func (m *Product) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Product.Unmarshal(m, b)
}
func (m *Product) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Product.Marshal(b, m, deterministic)
}
func (m *Product) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Product.Merge(m, src)
}
func (m *Product) XXX_Size() int {
	return xxx_messageInfo_Product.Size(m)
}
func (m *Product) XXX_DiscardUnknown() {
	xxx_messageInfo_Product.DiscardUnknown(m)
}

var xxx_messageInfo_Product proto.InternalMessageInfo

func (m *Product) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Product) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Request struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_14fbc13de7c38f78, []int{2}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

type ClientRequest struct {
	Nom                  string   `protobuf:"bytes,1,opt,name=nom,proto3" json:"nom,omitempty"`
	Prenom               string   `protobuf:"bytes,2,opt,name=prenom,proto3" json:"prenom,omitempty"`
	Dateofbirth          string   `protobuf:"bytes,3,opt,name=dateofbirth,proto3" json:"dateofbirth,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClientRequest) Reset()         { *m = ClientRequest{} }
func (m *ClientRequest) String() string { return proto.CompactTextString(m) }
func (*ClientRequest) ProtoMessage()    {}
func (*ClientRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_14fbc13de7c38f78, []int{3}
}

func (m *ClientRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientRequest.Unmarshal(m, b)
}
func (m *ClientRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientRequest.Marshal(b, m, deterministic)
}
func (m *ClientRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientRequest.Merge(m, src)
}
func (m *ClientRequest) XXX_Size() int {
	return xxx_messageInfo_ClientRequest.Size(m)
}
func (m *ClientRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ClientRequest proto.InternalMessageInfo

func (m *ClientRequest) GetNom() string {
	if m != nil {
		return m.Nom
	}
	return ""
}

func (m *ClientRequest) GetPrenom() string {
	if m != nil {
		return m.Prenom
	}
	return ""
}

func (m *ClientRequest) GetDateofbirth() string {
	if m != nil {
		return m.Dateofbirth
	}
	return ""
}

type Response struct {
	Product              *Product   `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	Products             []*Product `protobuf:"bytes,3,rep,name=products,proto3" json:"products,omitempty"`
	Errors               []*Error   `protobuf:"bytes,4,rep,name=errors,proto3" json:"errors,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_14fbc13de7c38f78, []int{4}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetProduct() *Product {
	if m != nil {
		return m.Product
	}
	return nil
}

func (m *Response) GetProducts() []*Product {
	if m != nil {
		return m.Products
	}
	return nil
}

func (m *Response) GetErrors() []*Error {
	if m != nil {
		return m.Errors
	}
	return nil
}

type Error struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_14fbc13de7c38f78, []int{5}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Error) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type Token struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Valid                bool     `protobuf:"varint,2,opt,name=valid,proto3" json:"valid,omitempty"`
	Errors               []*Error `protobuf:"bytes,3,rep,name=errors,proto3" json:"errors,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Token) Reset()         { *m = Token{} }
func (m *Token) String() string { return proto.CompactTextString(m) }
func (*Token) ProtoMessage()    {}
func (*Token) Descriptor() ([]byte, []int) {
	return fileDescriptor_14fbc13de7c38f78, []int{6}
}

func (m *Token) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Token.Unmarshal(m, b)
}
func (m *Token) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Token.Marshal(b, m, deterministic)
}
func (m *Token) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Token.Merge(m, src)
}
func (m *Token) XXX_Size() int {
	return xxx_messageInfo_Token.Size(m)
}
func (m *Token) XXX_DiscardUnknown() {
	xxx_messageInfo_Token.DiscardUnknown(m)
}

var xxx_messageInfo_Token proto.InternalMessageInfo

func (m *Token) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *Token) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

func (m *Token) GetErrors() []*Error {
	if m != nil {
		return m.Errors
	}
	return nil
}

func init() {
	proto.RegisterType((*Client)(nil), "product.Client")
	proto.RegisterType((*Product)(nil), "product.Product")
	proto.RegisterType((*Request)(nil), "product.Request")
	proto.RegisterType((*ClientRequest)(nil), "product.ClientRequest")
	proto.RegisterType((*Response)(nil), "product.Response")
	proto.RegisterType((*Error)(nil), "product.Error")
	proto.RegisterType((*Token)(nil), "product.Token")
}

func init() {
	proto.RegisterFile("proto/product/product.proto", fileDescriptor_14fbc13de7c38f78)
}

var fileDescriptor_14fbc13de7c38f78 = []byte{
	// 367 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x92, 0xc1, 0x4e, 0xc2, 0x40,
	0x10, 0x86, 0x2d, 0xa5, 0x05, 0x86, 0x88, 0x30, 0x31, 0xa6, 0x51, 0x0f, 0x64, 0x0f, 0xc6, 0x18,
	0x84, 0x04, 0x4f, 0x1e, 0x3c, 0x18, 0x63, 0xb8, 0x92, 0xea, 0x8d, 0x53, 0x69, 0xc7, 0xb8, 0x5a,
	0x76, 0xeb, 0x76, 0xe1, 0x29, 0x7c, 0x12, 0x9f, 0xd2, 0x74, 0xbb, 0xad, 0x4d, 0x24, 0x9e, 0x3c,
	0x31, 0xf3, 0xcd, 0x0c, 0xf3, 0xcf, 0xbf, 0x85, 0xb3, 0x4c, 0x49, 0x2d, 0x67, 0x99, 0x92, 0xc9,
	0x36, 0xd6, 0xd5, 0xef, 0xd4, 0x50, 0xec, 0xd8, 0x94, 0x29, 0xf0, 0x1f, 0x52, 0x4e, 0x42, 0xe3,
	0x10, 0x5c, 0x21, 0x37, 0x81, 0x33, 0x76, 0x2e, 0x7b, 0x61, 0x11, 0xe2, 0x09, 0xf8, 0x99, 0xa2,
	0x02, 0xb6, 0x0c, 0xb4, 0x19, 0x8e, 0xa1, 0x9f, 0x44, 0x9a, 0xe4, 0xcb, 0x9a, 0x2b, 0xfd, 0x1a,
	0xb8, 0xa6, 0xd8, 0x44, 0x78, 0x0e, 0xbd, 0x68, 0xfd, 0x16, 0x47, 0x2a, 0x11, 0x32, 0x68, 0x9b,
	0xfa, 0x0f, 0x60, 0xd7, 0xd0, 0x59, 0x96, 0xeb, 0x71, 0x00, 0x2d, 0x9e, 0xd8, 0x9d, 0x2d, 0x9e,
	0x20, 0x42, 0x5b, 0x44, 0x1b, 0xb2, 0x0b, 0x4d, 0xcc, 0x7a, 0xd0, 0x09, 0xe9, 0x63, 0x4b, 0xb9,
	0x66, 0x2b, 0x38, 0x2c, 0xd5, 0x5a, 0xf0, 0x9f, 0xa2, 0xd9, 0xa7, 0x03, 0xdd, 0x90, 0xf2, 0x4c,
	0x8a, 0x9c, 0xf0, 0x0a, 0x2a, 0x8b, 0xcc, 0x9f, 0xf7, 0xe7, 0xc3, 0x69, 0xe5, 0xa0, 0xd5, 0x1e,
	0x56, 0x0d, 0x38, 0x81, 0xae, 0x0d, 0xf3, 0xc0, 0x1d, 0xbb, 0x7b, 0x9b, 0xeb, 0x0e, 0xbc, 0x00,
	0x9f, 0x94, 0x92, 0x2a, 0x0f, 0xda, 0xa6, 0x77, 0x50, 0xf7, 0x3e, 0x16, 0x38, 0xb4, 0x55, 0x76,
	0x07, 0x9e, 0x01, 0x85, 0x27, 0xb1, 0x4c, 0xc8, 0xe8, 0xf0, 0x42, 0x13, 0x9b, 0x6b, 0x28, 0x8f,
	0x15, 0xcf, 0x34, 0x97, 0xc2, 0x9e, 0xda, 0x44, 0x6c, 0x05, 0xde, 0xb3, 0x7c, 0x27, 0x81, 0xc7,
	0xe0, 0xe9, 0x22, 0xb0, 0x26, 0x95, 0x49, 0x41, 0x77, 0x51, 0xca, 0x13, 0x33, 0xda, 0x0d, 0xcb,
	0xa4, 0xa1, 0xcd, 0xfd, 0x4b, 0xdb, 0xfc, 0xcb, 0x81, 0x81, 0xbd, 0xec, 0x89, 0xd4, 0x8e, 0xc7,
	0x84, 0x13, 0x70, 0x17, 0xa4, 0xf1, 0xd7, 0xe5, 0xa7, 0xa3, 0x9a, 0x54, 0xe6, 0xb2, 0x03, 0x9c,
	0x81, 0xbf, 0x20, 0x7d, 0x9f, 0xa6, 0x8d, 0x01, 0xfb, 0xa6, 0xfb, 0x07, 0x6e, 0x61, 0xb4, 0x20,
	0x5d, 0x3e, 0xfe, 0xb2, 0xb2, 0xf2, 0xa8, 0xee, 0x2c, 0x0b, 0x7b, 0x47, 0xd7, 0xbe, 0xf9, 0xe4,
	0x6f, 0xbe, 0x03, 0x00, 0x00, 0xff, 0xff, 0x95, 0x80, 0xb2, 0xa8, 0x11, 0x03, 0x00, 0x00,
}
