// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/product/product.proto

package product

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Product struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Product) Reset()         { *m = Product{} }
func (m *Product) String() string { return proto.CompactTextString(m) }
func (*Product) ProtoMessage()    {}
func (*Product) Descriptor() ([]byte, []int) {
	return fileDescriptor_14fbc13de7c38f78, []int{0}
}

func (m *Product) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Product.Unmarshal(m, b)
}
func (m *Product) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Product.Marshal(b, m, deterministic)
}
func (m *Product) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Product.Merge(m, src)
}
func (m *Product) XXX_Size() int {
	return xxx_messageInfo_Product.Size(m)
}
func (m *Product) XXX_DiscardUnknown() {
	xxx_messageInfo_Product.DiscardUnknown(m)
}

var xxx_messageInfo_Product proto.InternalMessageInfo

func (m *Product) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Product) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Request struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_14fbc13de7c38f78, []int{1}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

type Response struct {
	Product              *Product   `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	Products             []*Product `protobuf:"bytes,2,rep,name=products,proto3" json:"products,omitempty"`
	Errors               []*Error   `protobuf:"bytes,3,rep,name=errors,proto3" json:"errors,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_14fbc13de7c38f78, []int{2}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetProduct() *Product {
	if m != nil {
		return m.Product
	}
	return nil
}

func (m *Response) GetProducts() []*Product {
	if m != nil {
		return m.Products
	}
	return nil
}

func (m *Response) GetErrors() []*Error {
	if m != nil {
		return m.Errors
	}
	return nil
}

type Error struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_14fbc13de7c38f78, []int{3}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Error) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func init() {
	proto.RegisterType((*Product)(nil), "product.Product")
	proto.RegisterType((*Request)(nil), "product.Request")
	proto.RegisterType((*Response)(nil), "product.Response")
	proto.RegisterType((*Error)(nil), "product.Error")
}

func init() {
	proto.RegisterFile("proto/product/product.proto", fileDescriptor_14fbc13de7c38f78)
}

var fileDescriptor_14fbc13de7c38f78 = []byte{
	// 247 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0xb1, 0x4e, 0xc3, 0x30,
	0x10, 0x86, 0x49, 0x42, 0x93, 0xf6, 0x2a, 0x45, 0x70, 0x53, 0x04, 0x4b, 0xe4, 0x01, 0x21, 0x54,
	0x5a, 0xa9, 0xcc, 0x0c, 0x0c, 0xa8, 0x2b, 0x32, 0x4f, 0x00, 0xf1, 0x0d, 0x96, 0x4a, 0x2e, 0xd8,
	0x2e, 0x4f, 0xc1, 0x43, 0xa3, 0x1e, 0x76, 0x54, 0xa9, 0x99, 0xf2, 0xe7, 0xf3, 0x7f, 0x77, 0xff,
	0xd9, 0x70, 0x3b, 0x38, 0x0e, 0xbc, 0x19, 0x1c, 0x9b, 0x43, 0x17, 0xd2, 0x77, 0x2d, 0x14, 0xab,
	0xf8, 0xab, 0x1e, 0xa1, 0x7a, 0xfb, 0x97, 0x58, 0x43, 0x6e, 0x4d, 0x93, 0xb5, 0xd9, 0xfd, 0x42,
	0xe7, 0xd6, 0x20, 0xc2, 0x65, 0xff, 0xf1, 0x45, 0x4d, 0x2e, 0x44, 0xb4, 0x5a, 0x40, 0xa5, 0xe9,
	0xfb, 0x40, 0x3e, 0xa8, 0xdf, 0x0c, 0xe6, 0x9a, 0xfc, 0xc0, 0xbd, 0x27, 0x7c, 0x80, 0xd4, 0x51,
	0x1a, 0x2c, 0xb7, 0x57, 0xeb, 0x34, 0x30, 0xb6, 0xd7, 0xc9, 0x80, 0x2b, 0x98, 0x47, 0xe9, 0x9b,
	0xbc, 0x2d, 0x26, 0xcd, 0xa3, 0x03, 0xef, 0xa0, 0x24, 0xe7, 0xd8, 0xf9, 0xa6, 0x10, 0x6f, 0x3d,
	0x7a, 0x5f, 0x8f, 0x58, 0xc7, 0x53, 0xf5, 0x0c, 0x33, 0x01, 0xc7, 0xd8, 0x1d, 0x1b, 0x92, 0x1c,
	0x33, 0x2d, 0x1a, 0x5b, 0x58, 0x1a, 0xf2, 0x9d, 0xb3, 0x43, 0xb0, 0xdc, 0xc7, 0x8d, 0x4e, 0xd1,
	0x96, 0xa1, 0x8e, 0xb3, 0xdf, 0xc9, 0xfd, 0xd8, 0x8e, 0x70, 0x05, 0xc5, 0x8e, 0x02, 0x9e, 0x65,
	0xbb, 0xb9, 0x1e, 0x49, 0x5a, 0x5f, 0x5d, 0xe0, 0x06, 0xca, 0x1d, 0x85, 0x97, 0xfd, 0xfe, 0xa4,
	0x20, 0xde, 0xd4, 0x64, 0xc1, 0x67, 0x29, 0x0f, 0xf1, 0xf4, 0x17, 0x00, 0x00, 0xff, 0xff, 0xd2,
	0x08, 0xe1, 0xea, 0xa7, 0x01, 0x00, 0x00,
}
