// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/product/product.proto

package product

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Client struct {
	Nom                  string   `protobuf:"bytes,1,opt,name=nom,proto3" json:"nom,omitempty"`
	Prenom               string   `protobuf:"bytes,2,opt,name=prenom,proto3" json:"prenom,omitempty"`
	Dateofbirth          string   `protobuf:"bytes,3,opt,name=dateofbirth,proto3" json:"dateofbirth,omitempty"`
	Abjcardno            string   `protobuf:"bytes,4,opt,name=abjcardno,proto3" json:"abjcardno,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Client) Reset()         { *m = Client{} }
func (m *Client) String() string { return proto.CompactTextString(m) }
func (*Client) ProtoMessage()    {}
func (*Client) Descriptor() ([]byte, []int) {
	return fileDescriptor_14fbc13de7c38f78, []int{0}
}

func (m *Client) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Client.Unmarshal(m, b)
}
func (m *Client) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Client.Marshal(b, m, deterministic)
}
func (m *Client) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Client.Merge(m, src)
}
func (m *Client) XXX_Size() int {
	return xxx_messageInfo_Client.Size(m)
}
func (m *Client) XXX_DiscardUnknown() {
	xxx_messageInfo_Client.DiscardUnknown(m)
}

var xxx_messageInfo_Client proto.InternalMessageInfo

func (m *Client) GetNom() string {
	if m != nil {
		return m.Nom
	}
	return ""
}

func (m *Client) GetPrenom() string {
	if m != nil {
		return m.Prenom
	}
	return ""
}

func (m *Client) GetDateofbirth() string {
	if m != nil {
		return m.Dateofbirth
	}
	return ""
}

func (m *Client) GetAbjcardno() string {
	if m != nil {
		return m.Abjcardno
	}
	return ""
}

type Product struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Product) Reset()         { *m = Product{} }
func (m *Product) String() string { return proto.CompactTextString(m) }
func (*Product) ProtoMessage()    {}
func (*Product) Descriptor() ([]byte, []int) {
	return fileDescriptor_14fbc13de7c38f78, []int{1}
}

func (m *Product) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Product.Unmarshal(m, b)
}
func (m *Product) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Product.Marshal(b, m, deterministic)
}
func (m *Product) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Product.Merge(m, src)
}
func (m *Product) XXX_Size() int {
	return xxx_messageInfo_Product.Size(m)
}
func (m *Product) XXX_DiscardUnknown() {
	xxx_messageInfo_Product.DiscardUnknown(m)
}

var xxx_messageInfo_Product proto.InternalMessageInfo

func (m *Product) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Product) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Police struct {
	Police               string   `protobuf:"bytes,1,opt,name=police,proto3" json:"police,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Police) Reset()         { *m = Police{} }
func (m *Police) String() string { return proto.CompactTextString(m) }
func (*Police) ProtoMessage()    {}
func (*Police) Descriptor() ([]byte, []int) {
	return fileDescriptor_14fbc13de7c38f78, []int{2}
}

func (m *Police) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Police.Unmarshal(m, b)
}
func (m *Police) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Police.Marshal(b, m, deterministic)
}
func (m *Police) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Police.Merge(m, src)
}
func (m *Police) XXX_Size() int {
	return xxx_messageInfo_Police.Size(m)
}
func (m *Police) XXX_DiscardUnknown() {
	xxx_messageInfo_Police.DiscardUnknown(m)
}

var xxx_messageInfo_Police proto.InternalMessageInfo

func (m *Police) GetPolice() string {
	if m != nil {
		return m.Police
	}
	return ""
}

type Etat struct {
	Police               string   `protobuf:"bytes,1,opt,name=police,proto3" json:"police,omitempty"`
	Datedebuteffet       string   `protobuf:"bytes,2,opt,name=datedebuteffet,proto3" json:"datedebuteffet,omitempty"`
	Datefineffet         string   `protobuf:"bytes,3,opt,name=datefineffet,proto3" json:"datefineffet,omitempty"`
	Libelleproduit       string   `protobuf:"bytes,4,opt,name=libelleproduit,proto3" json:"libelleproduit,omitempty"`
	Modereglement        string   `protobuf:"bytes,5,opt,name=modereglement,proto3" json:"modereglement,omitempty"`
	Fractionnement       string   `protobuf:"bytes,6,opt,name=fractionnement,proto3" json:"fractionnement,omitempty"`
	Numeropayeur         string   `protobuf:"bytes,7,opt,name=numeropayeur,proto3" json:"numeropayeur,omitempty"`
	Nompayeur            string   `protobuf:"bytes,8,opt,name=nompayeur,proto3" json:"nompayeur,omitempty"`
	Telephone            string   `protobuf:"bytes,9,opt,name=telephone,proto3" json:"telephone,omitempty"`
	Profession           string   `protobuf:"bytes,10,opt,name=profession,proto3" json:"profession,omitempty"`
	Adresse              string   `protobuf:"bytes,11,opt,name=adresse,proto3" json:"adresse,omitempty"`
	Datenaissance        string   `protobuf:"bytes,12,opt,name=datenaissance,proto3" json:"datenaissance,omitempty"`
	Lieunaissance        string   `protobuf:"bytes,13,opt,name=lieunaissance,proto3" json:"lieunaissance,omitempty"`
	Nomsouscripteur      string   `protobuf:"bytes,14,opt,name=nomsouscripteur,proto3" json:"nomsouscripteur,omitempty"`
	Quittance            string   `protobuf:"bytes,15,opt,name=quittance,proto3" json:"quittance,omitempty"`
	Prime                string   `protobuf:"bytes,16,opt,name=prime,proto3" json:"prime,omitempty"`
	Datecomptable        string   `protobuf:"bytes,17,opt,name=datecomptable,proto3" json:"datecomptable,omitempty"`
	Datequittance        string   `protobuf:"bytes,18,opt,name=datequittance,proto3" json:"datequittance,omitempty"`
	Etatquittance        string   `protobuf:"bytes,19,opt,name=etatquittance,proto3" json:"etatquittance,omitempty"`
	Montantsolde         string   `protobuf:"bytes,20,opt,name=montantsolde,proto3" json:"montantsolde,omitempty"`
	Montantimpaye        string   `protobuf:"bytes,21,opt,name=montantimpaye,proto3" json:"montantimpaye,omitempty"`
	Nombresolde          string   `protobuf:"bytes,22,opt,name=nombresolde,proto3" json:"nombresolde,omitempty"`
	Nombreimpaye         string   `protobuf:"bytes,23,opt,name=nombreimpaye,proto3" json:"nombreimpaye,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Etat) Reset()         { *m = Etat{} }
func (m *Etat) String() string { return proto.CompactTextString(m) }
func (*Etat) ProtoMessage()    {}
func (*Etat) Descriptor() ([]byte, []int) {
	return fileDescriptor_14fbc13de7c38f78, []int{3}
}

func (m *Etat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Etat.Unmarshal(m, b)
}
func (m *Etat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Etat.Marshal(b, m, deterministic)
}
func (m *Etat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Etat.Merge(m, src)
}
func (m *Etat) XXX_Size() int {
	return xxx_messageInfo_Etat.Size(m)
}
func (m *Etat) XXX_DiscardUnknown() {
	xxx_messageInfo_Etat.DiscardUnknown(m)
}

var xxx_messageInfo_Etat proto.InternalMessageInfo

func (m *Etat) GetPolice() string {
	if m != nil {
		return m.Police
	}
	return ""
}

func (m *Etat) GetDatedebuteffet() string {
	if m != nil {
		return m.Datedebuteffet
	}
	return ""
}

func (m *Etat) GetDatefineffet() string {
	if m != nil {
		return m.Datefineffet
	}
	return ""
}

func (m *Etat) GetLibelleproduit() string {
	if m != nil {
		return m.Libelleproduit
	}
	return ""
}

func (m *Etat) GetModereglement() string {
	if m != nil {
		return m.Modereglement
	}
	return ""
}

func (m *Etat) GetFractionnement() string {
	if m != nil {
		return m.Fractionnement
	}
	return ""
}

func (m *Etat) GetNumeropayeur() string {
	if m != nil {
		return m.Numeropayeur
	}
	return ""
}

func (m *Etat) GetNompayeur() string {
	if m != nil {
		return m.Nompayeur
	}
	return ""
}

func (m *Etat) GetTelephone() string {
	if m != nil {
		return m.Telephone
	}
	return ""
}

func (m *Etat) GetProfession() string {
	if m != nil {
		return m.Profession
	}
	return ""
}

func (m *Etat) GetAdresse() string {
	if m != nil {
		return m.Adresse
	}
	return ""
}

func (m *Etat) GetDatenaissance() string {
	if m != nil {
		return m.Datenaissance
	}
	return ""
}

func (m *Etat) GetLieunaissance() string {
	if m != nil {
		return m.Lieunaissance
	}
	return ""
}

func (m *Etat) GetNomsouscripteur() string {
	if m != nil {
		return m.Nomsouscripteur
	}
	return ""
}

func (m *Etat) GetQuittance() string {
	if m != nil {
		return m.Quittance
	}
	return ""
}

func (m *Etat) GetPrime() string {
	if m != nil {
		return m.Prime
	}
	return ""
}

func (m *Etat) GetDatecomptable() string {
	if m != nil {
		return m.Datecomptable
	}
	return ""
}

func (m *Etat) GetDatequittance() string {
	if m != nil {
		return m.Datequittance
	}
	return ""
}

func (m *Etat) GetEtatquittance() string {
	if m != nil {
		return m.Etatquittance
	}
	return ""
}

func (m *Etat) GetMontantsolde() string {
	if m != nil {
		return m.Montantsolde
	}
	return ""
}

func (m *Etat) GetMontantimpaye() string {
	if m != nil {
		return m.Montantimpaye
	}
	return ""
}

func (m *Etat) GetNombresolde() string {
	if m != nil {
		return m.Nombresolde
	}
	return ""
}

func (m *Etat) GetNombreimpaye() string {
	if m != nil {
		return m.Nombreimpaye
	}
	return ""
}

type Request struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_14fbc13de7c38f78, []int{4}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

type ClientRequest struct {
	Nom                  string   `protobuf:"bytes,1,opt,name=nom,proto3" json:"nom,omitempty"`
	Prenom               string   `protobuf:"bytes,2,opt,name=prenom,proto3" json:"prenom,omitempty"`
	Dateofbirth          string   `protobuf:"bytes,3,opt,name=dateofbirth,proto3" json:"dateofbirth,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClientRequest) Reset()         { *m = ClientRequest{} }
func (m *ClientRequest) String() string { return proto.CompactTextString(m) }
func (*ClientRequest) ProtoMessage()    {}
func (*ClientRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_14fbc13de7c38f78, []int{5}
}

func (m *ClientRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientRequest.Unmarshal(m, b)
}
func (m *ClientRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientRequest.Marshal(b, m, deterministic)
}
func (m *ClientRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientRequest.Merge(m, src)
}
func (m *ClientRequest) XXX_Size() int {
	return xxx_messageInfo_ClientRequest.Size(m)
}
func (m *ClientRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ClientRequest proto.InternalMessageInfo

func (m *ClientRequest) GetNom() string {
	if m != nil {
		return m.Nom
	}
	return ""
}

func (m *ClientRequest) GetPrenom() string {
	if m != nil {
		return m.Prenom
	}
	return ""
}

func (m *ClientRequest) GetDateofbirth() string {
	if m != nil {
		return m.Dateofbirth
	}
	return ""
}

type Response struct {
	Product              *Product   `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	Etat                 string     `protobuf:"bytes,2,opt,name=etat,proto3" json:"etat,omitempty"`
	Products             []*Product `protobuf:"bytes,3,rep,name=products,proto3" json:"products,omitempty"`
	Errors               []*Error   `protobuf:"bytes,4,rep,name=errors,proto3" json:"errors,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_14fbc13de7c38f78, []int{6}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetProduct() *Product {
	if m != nil {
		return m.Product
	}
	return nil
}

func (m *Response) GetEtat() string {
	if m != nil {
		return m.Etat
	}
	return ""
}

func (m *Response) GetProducts() []*Product {
	if m != nil {
		return m.Products
	}
	return nil
}

func (m *Response) GetErrors() []*Error {
	if m != nil {
		return m.Errors
	}
	return nil
}

type Error struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_14fbc13de7c38f78, []int{7}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Error) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type Token struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Valid                bool     `protobuf:"varint,2,opt,name=valid,proto3" json:"valid,omitempty"`
	Errors               []*Error `protobuf:"bytes,3,rep,name=errors,proto3" json:"errors,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Token) Reset()         { *m = Token{} }
func (m *Token) String() string { return proto.CompactTextString(m) }
func (*Token) ProtoMessage()    {}
func (*Token) Descriptor() ([]byte, []int) {
	return fileDescriptor_14fbc13de7c38f78, []int{8}
}

func (m *Token) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Token.Unmarshal(m, b)
}
func (m *Token) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Token.Marshal(b, m, deterministic)
}
func (m *Token) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Token.Merge(m, src)
}
func (m *Token) XXX_Size() int {
	return xxx_messageInfo_Token.Size(m)
}
func (m *Token) XXX_DiscardUnknown() {
	xxx_messageInfo_Token.DiscardUnknown(m)
}

var xxx_messageInfo_Token proto.InternalMessageInfo

func (m *Token) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *Token) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

func (m *Token) GetErrors() []*Error {
	if m != nil {
		return m.Errors
	}
	return nil
}

func init() {
	proto.RegisterType((*Client)(nil), "product.Client")
	proto.RegisterType((*Product)(nil), "product.Product")
	proto.RegisterType((*Police)(nil), "product.Police")
	proto.RegisterType((*Etat)(nil), "product.Etat")
	proto.RegisterType((*Request)(nil), "product.Request")
	proto.RegisterType((*ClientRequest)(nil), "product.ClientRequest")
	proto.RegisterType((*Response)(nil), "product.Response")
	proto.RegisterType((*Error)(nil), "product.Error")
	proto.RegisterType((*Token)(nil), "product.Token")
}

func init() {
	proto.RegisterFile("proto/product/product.proto", fileDescriptor_14fbc13de7c38f78)
}

var fileDescriptor_14fbc13de7c38f78 = []byte{
	// 711 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x95, 0xcd, 0x6e, 0xdb, 0x38,
	0x10, 0xc7, 0xd7, 0x5f, 0xb2, 0x3d, 0x89, 0x9d, 0x84, 0x9b, 0xcd, 0x12, 0xbb, 0x45, 0x61, 0x08,
	0x41, 0x10, 0x14, 0x69, 0x02, 0xa4, 0x40, 0x81, 0x1e, 0x7a, 0x28, 0x82, 0x20, 0xd7, 0x40, 0xed,
	0x2d, 0x27, 0x4a, 0x1a, 0x37, 0x6c, 0x25, 0x52, 0x21, 0xa9, 0x00, 0x7d, 0x9b, 0x9e, 0xfa, 0x60,
	0x7d, 0x92, 0x82, 0x1f, 0xfa, 0x70, 0xea, 0xf6, 0xd4, 0x93, 0x39, 0xbf, 0xf9, 0xcf, 0x70, 0x86,
	0xe2, 0xd0, 0xf0, 0x7f, 0xa5, 0xa4, 0x91, 0x17, 0x95, 0x92, 0x79, 0x9d, 0x99, 0xe6, 0xf7, 0xdc,
	0x51, 0x32, 0x0d, 0x66, 0xac, 0x20, 0xba, 0x2a, 0x38, 0x0a, 0x43, 0xf6, 0x61, 0x24, 0x64, 0x49,
	0x07, 0xab, 0xc1, 0xe9, 0x3c, 0xb1, 0x4b, 0x72, 0x04, 0x51, 0xa5, 0xd0, 0xc2, 0xa1, 0x83, 0xc1,
	0x22, 0x2b, 0xd8, 0xc9, 0x99, 0x41, 0xb9, 0x4e, 0xb9, 0x32, 0xf7, 0x74, 0xe4, 0x9c, 0x7d, 0x44,
	0x9e, 0xc1, 0x9c, 0xa5, 0x9f, 0x32, 0xa6, 0x72, 0x21, 0xe9, 0xd8, 0xf9, 0x3b, 0x10, 0xbf, 0x84,
	0xe9, 0xad, 0xdf, 0x9e, 0x2c, 0x61, 0xc8, 0xf3, 0xb0, 0xe7, 0x90, 0xe7, 0x84, 0xc0, 0x58, 0xb0,
	0x12, 0xc3, 0x86, 0x6e, 0x1d, 0xaf, 0x20, 0xba, 0x95, 0x05, 0xcf, 0xd0, 0x15, 0xe4, 0x56, 0x21,
	0x22, 0x58, 0xf1, 0xb7, 0x08, 0xc6, 0xd7, 0x86, 0x99, 0x5f, 0x09, 0xc8, 0x09, 0x2c, 0x6d, 0x79,
	0x39, 0xa6, 0xb5, 0xc1, 0xf5, 0x1a, 0x4d, 0xd8, 0xe0, 0x09, 0x25, 0x31, 0xec, 0x5a, 0xb2, 0xe6,
	0xc2, 0xab, 0x7c, 0x6b, 0x1b, 0xcc, 0xe6, 0x2a, 0x78, 0x8a, 0x45, 0x81, 0xee, 0x0c, 0xb9, 0x09,
	0x0d, 0x3e, 0xa1, 0xe4, 0x18, 0x16, 0xa5, 0xcc, 0x51, 0xe1, 0xc7, 0x02, 0x4b, 0x14, 0x86, 0x4e,
	0x9c, 0x6c, 0x13, 0xda, 0x6c, 0x6b, 0xc5, 0x32, 0xc3, 0xa5, 0x10, 0x5e, 0x16, 0xf9, 0x6c, 0x9b,
	0xd4, 0x56, 0x26, 0xea, 0x12, 0x95, 0xac, 0xd8, 0x17, 0xac, 0x15, 0x9d, 0xfa, 0xca, 0xfa, 0xcc,
	0x9e, 0xba, 0x90, 0x65, 0x10, 0xcc, 0xfc, 0xa9, 0xb7, 0xc0, 0x7a, 0x0d, 0x16, 0x58, 0xdd, 0x4b,
	0x81, 0x74, 0xee, 0xbd, 0x2d, 0x20, 0xcf, 0x01, 0x2a, 0x25, 0xd7, 0xa8, 0x35, 0x97, 0x82, 0x82,
	0x73, 0xf7, 0x08, 0xa1, 0x30, 0x65, 0xb9, 0x42, 0xad, 0x91, 0xee, 0x38, 0x67, 0x63, 0xda, 0x3e,
	0xed, 0xf9, 0x08, 0xc6, 0xb5, 0x66, 0x22, 0x43, 0xba, 0xeb, 0xfb, 0xdc, 0x80, 0x56, 0x55, 0x70,
	0xac, 0x3b, 0xd5, 0xc2, 0xab, 0x36, 0x20, 0x39, 0x85, 0x3d, 0x21, 0x4b, 0x2d, 0x6b, 0x9d, 0x29,
	0x5e, 0x19, 0xdb, 0xc7, 0xd2, 0xe9, 0x9e, 0x62, 0xdb, 0xcd, 0x43, 0xcd, 0x8d, 0x71, 0xb9, 0xf6,
	0x7c, 0x37, 0x2d, 0x20, 0x87, 0x30, 0xa9, 0x14, 0x2f, 0x91, 0xee, 0x3b, 0x8f, 0x37, 0x9a, 0x4a,
	0x33, 0x59, 0x56, 0x86, 0xa5, 0x05, 0xd2, 0x83, 0xae, 0xd2, 0x16, 0x36, 0xaa, 0x2e, 0x3b, 0xe9,
	0x54, 0xdd, 0x0e, 0xc7, 0xb0, 0x40, 0xc3, 0x4c, 0xa7, 0xfa, 0xdb, 0xab, 0x36, 0xa0, 0xfd, 0x6a,
	0xa5, 0x14, 0x86, 0x09, 0xa3, 0x65, 0x91, 0x23, 0x3d, 0xf4, 0x5f, 0xad, 0xcf, 0xfc, 0x3d, 0x71,
	0x36, 0x77, 0x9f, 0x8a, 0xfe, 0xd3, 0xdc, 0x93, 0x1e, 0xb4, 0x33, 0x27, 0x64, 0x99, 0x2a, 0xf4,
	0x89, 0x8e, 0xfc, 0xcc, 0xf5, 0x90, 0xbb, 0x21, 0xce, 0x0c, 0x69, 0xfe, 0x0d, 0x37, 0xa4, 0xc7,
	0xe2, 0x39, 0x4c, 0x13, 0x7c, 0xa8, 0x51, 0x9b, 0xf8, 0x0e, 0x16, 0x7e, 0xf0, 0x03, 0xf8, 0x93,
	0xf3, 0x1f, 0x7f, 0x1d, 0xc0, 0x2c, 0x41, 0x5d, 0x49, 0xa1, 0x91, 0xbc, 0x80, 0xe6, 0xb5, 0x71,
	0xc9, 0x77, 0x2e, 0xf7, 0xcf, 0x9b, 0xc7, 0x28, 0x3c, 0x03, 0x49, 0x23, 0xb0, 0xf3, 0x6f, 0x4f,
	0xb0, 0x99, 0x7f, 0xbb, 0x26, 0x67, 0x30, 0x0b, 0x6e, 0x4d, 0x47, 0xab, 0xd1, 0xd6, 0x04, 0xad,
	0x82, 0x9c, 0x40, 0x84, 0x4a, 0x49, 0xa5, 0xe9, 0xd8, 0x69, 0x97, 0xad, 0xf6, 0xda, 0xe2, 0x24,
	0x78, 0xe3, 0xb7, 0x30, 0x71, 0xc0, 0x6e, 0x99, 0xc9, 0xdc, 0xbf, 0x18, 0x93, 0xc4, 0xad, 0x5d,
	0x87, 0xe8, 0x2f, 0x9b, 0x1d, 0x87, 0x61, 0xe8, 0xb0, 0x43, 0xf1, 0x1d, 0x4c, 0x3e, 0xc8, 0xcf,
	0x28, 0xec, 0x55, 0x33, 0x76, 0x11, 0x0e, 0xce, 0x1b, 0x96, 0x3e, 0xb2, 0x82, 0xe7, 0x2e, 0x74,
	0x96, 0x78, 0xa3, 0x57, 0xdb, 0xe8, 0x77, 0xb5, 0x5d, 0x7e, 0x1f, 0xc0, 0x32, 0x74, 0xf6, 0x1e,
	0xd5, 0xa3, 0x7d, 0xc1, 0xce, 0x60, 0x74, 0x83, 0x86, 0xfc, 0xd4, 0xf9, 0x7f, 0x07, 0x2d, 0x69,
	0x0e, 0x3c, 0xfe, 0x8b, 0x5c, 0x40, 0x74, 0x83, 0xe6, 0x5d, 0x51, 0xf4, 0x02, 0xc2, 0x77, 0xde,
	0x1e, 0xf0, 0x1a, 0x96, 0x37, 0x68, 0xae, 0xa4, 0xe1, 0x9a, 0xd9, 0xfe, 0x34, 0xd9, 0xeb, 0x76,
	0x72, 0x6f, 0xe8, 0xf6, 0xb8, 0x37, 0x70, 0x60, 0xe3, 0xdc, 0x45, 0xba, 0x6d, 0x3e, 0x41, 0x17,
	0xea, 0x1d, 0x5b, 0x43, 0xd3, 0xc8, 0xfd, 0x13, 0xbd, 0xfa, 0x11, 0x00, 0x00, 0xff, 0xff, 0xfe,
	0x7b, 0x15, 0x27, 0xa8, 0x06, 0x00, 0x00,
}
